# Generated by Django 4.2.9 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='LogNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(blank=True, null=True, verbose_name='last datetime send')),
                ('status', models.CharField(blank=True, null=True, verbose_name='send status')),
                ('server_answer', models.CharField(blank=True, null=True, verbose_name='server status')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_massage', models.CharField(max_length=50, verbose_name='theme')),
                ('text_massage', models.TextField(verbose_name='text')),
                ('send_time', models.TimeField(verbose_name='newsletter time')),
                ('period', models.CharField(choices=[('PER_DAY', 'every day'), ('PER_WEEK', 'every week'), ('PER_MONTH', 'every month')], verbose_name='period')),
                ('status', models.CharField(choices=[('CREATE', 'create'), ('END', 'end'), ('IN_WORK', 'in work')], default='CREATE', verbose_name='status')),
                ('clients', models.ManyToManyField(to='mailing.client', verbose_name='clients')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
    ]
