# Generated by Django 4.2.9 on 2024-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(verbose_name='last datetime send')),
                ('status', models.CharField(verbose_name='send status')),
                ('server_answer', models.CharField(null=True, verbose_name='server status')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='theme')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'massage',
                'verbose_name_plural': 'massages',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='newsletter time')),
                ('period', models.CharField(choices=[('PER_DAY', 'every day'), ('PER_WEEK', 'every week'), ('PER_MONTH', 'every month')], verbose_name='period')),
                ('status', models.CharField(choices=[('CREATE', 'create'), ('END', 'end'), ('IN_WORK', 'in work')], verbose_name='status')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
    ]
