# Generated by Django 4.2.9 on 2024-02-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognewsletter',
            name='server_answer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='server status'),
        ),
        migrations.AlterField(
            model_name='lognewsletter',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='send status'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('PER_DAY', 'every day'), ('PER_WEEK', 'every week'), ('PER_MONTH', 'every month')], max_length=30, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CREATE', 'create'), ('END', 'end'), ('IN_WORK', 'in work')], default='CREATE', max_length=30, verbose_name='status'),
        ),
    ]
