# Generated by Django 4.2.9 on 2024-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='image')),
                ('views_count', models.IntegerField(default=0, verbose_name='views_count')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='published_at')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
